### ISSUE TITLE
How do I use this thing?

### ISSUE THREAD

**Issue by wileymc** [dav1do/van-finder#1]
Also in the market for a van.  How do I spin this thing up?

**Comment by dav1do** [comment]
well.. I only set it up to work with one site and then got bored 🙃 a bunch of sites return html that I was too lazy to parse (and sometimes require a client side token that I didn't mess with)... but the gist is to update your .env to match the .env.sample with real values (you need to allow 'less secure apps' so you can avoid 2factor auth with gmail. see [this article](https://webewizard.com/2019/09/17/Using-Lettre-With-Gmail/)). I also hardcoded the [query params](https://github.com/dav1do/van-finder/blob/e4b3c58761ab028220ed2be04ac209c3eee3ccdd/van-finder/src/sites/van_camper.rs#L16) 

but once that is set up, you `cargo run` and it will check the highwater file (empty first time) and then email you a list of all the vans that match the query. it sleeps for a day by default and will repeat the query but stop as soon as it hit the highwater mark van (not super smart.. and I don't think I updated it to handle the vans getting taken down so using created timestamps instead). 

if you don't like it running in the background, you can stop it and just run it manually when you want to see if there are any updates.

I'll try to update the readme so it's not worthless .. never spent the time to make it flexible. could update the site client to take query params and use `clap` to make a nice cli for it. I've been meaning to start looking again so it might move up the priority list...

**Comment by dav1do** [comment]
updated the [readme](https://github.com/dav1do/van-finder/commit/3f1c839c354f7305f0cd225a939b049e6f4f3437)

**Comment by wileymc** [comment]
cargo run #vanlife
